spring:
  profiles:
    active: dev   # dev 开发环境  test 测试环境  prod 生产环境
  application:
    name: service-discovery
server:
  port: 8500
#公共配置

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS