spring:
  profiles:
    active: dev
  application:
    name: service-auth
eureka:
  instance:
    appname: service-auth
server:
  port: 8520

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true  #开启下划线转驼峰
